CREATE DATABASE IF NOT EXISTS p3_coachboard;
USE p3_coachboard;

DROP TABLE IF EXISTS SUIVI;
DROP TABLE IF EXISTS SEANCES_EXERCICES;
DROP TABLE IF EXISTS ELEVES_PROGRAMMES;
DROP TABLE IF EXISTS SEANCES;
DROP TABLE IF EXISTS EXERCICES;
DROP TABLE IF EXISTS PROGRAMMES;
DROP TABLE IF EXISTS ELEVES;
DROP TABLE IF EXISTS COACH;
DROP TABLE IF EXISTS items;

CREATE TABLE COACH (
  ID_COACH INT PRIMARY KEY AUTO_INCREMENT,
  PRENOM VARCHAR(50) NOT NULL,
  NOM VARCHAR (50) NOT NULL,
  EMAIL VARCHAR(100) NOT NULL UNIQUE,
  MOT_DE_PASSE VARCHAR(255) NOT NULL
);

CREATE TABLE EXERCICES (
  ID_EXERCICE INT PRIMARY KEY AUTO_INCREMENT,
  NOM VARCHAR(100) NOT NULL,
  DESCRIPTION TEXT,
  GROUPE_MUSCULAIRE VARCHAR(100),
  TYPE VARCHAR(50),
  IMAGE_URL VARCHAR(255),
  ID_COACH INT NOT NULL,
  FOREIGN KEY (ID_COACH) REFERENCES COACH(ID_COACH)
);

CREATE TABLE PROGRAMMES (
  ID_PROGRAMME INT PRIMARY KEY AUTO_INCREMENT,
  NOM VARCHAR(100) NOT NULL,
  OBJECTIF VARCHAR(255),
  DUREE INT,
  ID_COACH INT NOT NULL,
  FOREIGN KEY (ID_COACH) REFERENCES COACH(ID_COACH)
);

CREATE TABLE SEANCES (
  ID_SEANCE INT PRIMARY KEY AUTO_INCREMENT,
  TITRE VARCHAR(100) NOT NULL,
  JOUR VARCHAR(20),
  ORDRE INT,
  ID_PROGRAMME INT NOT NULL,
  FOREIGN KEY (ID_PROGRAMME) REFERENCES PROGRAMMES(ID_PROGRAMME)
);

CREATE TABLE ELEVES (
  ID_ELEVE INT PRIMARY KEY AUTO_INCREMENT,
  PRENOM VARCHAR(50) NOT NULL,
  NOM VARCHAR (50) NOT NULL,
  EMAIL VARCHAR(100) NOT NULL UNIQUE,
  MOT_DE_PASSE VARCHAR(255) NOT NULL,
  AGE INT,
  POIDS_INITIAL DECIMAL(5,2),
  TAILLE DECIMAL(5,2),
  OBJECTIF VARCHAR(255),
  NIVEAU VARCHAR (50)
);

CREATE TABLE ELEVES_PROGRAMMES (
  ID_ELEVE_PROGRAMME INT PRIMARY KEY AUTO_INCREMENT,
  DATE_DEBUT DATE,
  STATUT VARCHAR(50),
  DATE_FIN DATE,
  ID_PROGRAMME INT NOT NULL,
  ID_ELEVE INT NOT NULL,
  FOREIGN KEY (ID_PROGRAMME) REFERENCES PROGRAMMES(ID_PROGRAMME),
  FOREIGN KEY (ID_ELEVE) REFERENCES ELEVES(ID_ELEVE)
);

CREATE TABLE SEANCES_EXERCICES (
  ID_SEANCES_EXERCICES INT PRIMARY KEY AUTO_INCREMENT,
  ID_SEANCE INT NOT NULL,
  ID_EXERCICE INT NOT NULL,
  SERIES INT,
  REPS INT,
  CHARGE DECIMAL(5,2),
  REPOS INT,
  ORDRE INT,
  FOREIGN KEY (ID_SEANCE) REFERENCES SEANCES(ID_SEANCE),
  FOREIGN KEY (ID_EXERCICE) REFERENCES EXERCICES(ID_EXERCICE)
  
);


 CREATE TABLE SUIVI (
  ID_SUIVI INT PRIMARY KEY AUTO_INCREMENT,
  CHARGE_SOULEVEE DECIMAL(5,2),
  REPS_REELLE INT,
  POIDS_CORPOREL DECIMAL(5,2),
  RESSENTI VARCHAR(50),
  COMMENTAIRES TEXT,
  DATE DATE NOT NULL,
  ID_SEANCE INT NOT NULL,
  ID_SEANCES_EXERCICES INT NOT NULL,
  ID_ELEVE_PROGRAMME INT NOT NULL,
  FOREIGN KEY (ID_SEANCE) REFERENCES SEANCES(ID_SEANCE),
  FOREIGN KEY (ID_SEANCES_EXERCICES) REFERENCES SEANCES_EXERCICES(ID_SEANCES_EXERCICES),
  FOREIGN KEY (ID_ELEVE_PROGRAMME) REFERENCES ELEVES_PROGRAMMES(ID_ELEVE_PROGRAMME)

 );